version: '3'

services:

  php-apache:
    build:
      ./php 
    ports:
      - 80:80 
    volumes:
      - ./src:/var/www/html 
    depends_on:
      - mysql 

  mysql:
    image: mysql 
    container_name: DB
    volumes: 
      - "./sql/init.sql:/docker-entrypoint-initdb.d/1.sql" 
    environment:
      MYSQL_ROOT_PASSWORD: password
    